[build]
builder = "nixpacks"
buildCommand = "cd apps/backend && npm install && npm run build"

[deploy]
startCommand = "cd apps/backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure" 